use std::{
    collections::{BTreeMap, HashMap},
    path::{Path, PathBuf},
    time::Duration,
};

use anyhow::{Context, Result, anyhow};
use clap::Parser;
use k8s_openapi::{
    api::resource::v1 as resv1,
    apimachinery::pkg::{api::resource::Quantity, apis::meta::v1::ObjectMeta},
};
use kube::{
    Api, Client,
    api::{Patch, PatchParams},
};
use nvml_wrapper::{Nvml, enums::device::DeviceArchitecture, error::NvmlError};
use tokio::{
    net::UnixListener,
    select,
    sync::watch,
    time::sleep,
};
use tokio_stream::wrappers::UnixListenerStream;
use tonic::{Request, Response, Status, async_trait, transport::Server};
use tracing::{error, info, warn};

mod pb {
    pub mod dra {
        tonic::include_proto!("k8s.io.kubelet.pkg.apis.dra.v1");
    }
    pub mod registration {
        tonic::include_proto!("pluginregistration");
    }
}

const DEFAULT_DRIVER_NAME: &str = "gpu.nvidia.com";
const DEFAULT_DEVICE_CLASS: &str = "gpu.nvidia.com";
const DEFAULT_EXTENDED_RESOURCE: &str = "nvidia.com/gpu";
const DEFAULT_KUBELET_DIR: &str = "/var/lib/kubelet";
const DRA_API_VERSION: &str = "v1";

#[derive(Parser, Debug, Clone)]
#[command(author, version, about, long_about = None)]
struct Args {
    /// DRA driver name (DNS subdomain) published in ResourceSlice and DeviceClass.
    #[arg(long, default_value = DEFAULT_DRIVER_NAME)]
    driver_name: String,

    /// DeviceClass name to ensure exists with extendedResourceName mapping.
    /// Empty disables DeviceClass management (admin-managed).
    #[arg(long, default_value = DEFAULT_DEVICE_CLASS)]
    device_class: String,

    /// Extended resource name for backwards compatibility (KEP-5004).
    /// Pods using `resources.limits.<name>: N` are translated to a ResourceClaim
    /// against the DeviceClass above. Empty disables the mapping.
    #[arg(long, default_value = DEFAULT_EXTENDED_RESOURCE)]
    extended_resource_name: String,

    /// kubelet root dir (sockets live under plugins/ and plugins_registry/).
    #[arg(long, default_value = DEFAULT_KUBELET_DIR)]
    kubelet_dir: String,

    /// Node name. Defaults to NODE_NAME env var (downward API).
    #[arg(long, env = "NODE_NAME")]
    node_name: String,

    /// Skip advertising GPUs whose display is currently active (workstation GPU 0).
    #[arg(long)]
    exclude_display_gpus: bool,

    /// Comma-separated GPU indices to exclude (e.g. "0,2").
    #[arg(long, value_delimiter = ',')]
    exclude_indices: Vec<u32>,

    /// CDI device-name prefix. Each GPU is advertised as `<prefix>=<index>`.
    /// Must match the CDI specs installed on the host (typically generated by
    /// `nvidia-ctk cdi generate`).
    #[arg(long, default_value = "nvidia.com/gpu")]
    cdi_kind: String,

    /// Path to libnvidia-ml.so (defaults to the loader search path).
    /// On NixOS hosts, typically `/run/opengl-driver/lib/libnvidia-ml.so.1`.
    #[arg(long)]
    nvml_lib_path: Option<String>,
}

#[derive(Debug, Clone)]
struct GpuInfo {
    index: u32,
    uuid: String,
    name: String,
    architecture: String,
    memory_bytes: u64,
    display_active: bool,
    compute_major: i32,
    compute_minor: i32,
}

fn architecture_str(a: DeviceArchitecture) -> &'static str {
    match a {
        DeviceArchitecture::Kepler => "kepler",
        DeviceArchitecture::Maxwell => "maxwell",
        DeviceArchitecture::Pascal => "pascal",
        DeviceArchitecture::Volta => "volta",
        DeviceArchitecture::Turing => "turing",
        DeviceArchitecture::Ampere => "ampere",
        DeviceArchitecture::Ada => "ada",
        DeviceArchitecture::Hopper => "hopper",
        DeviceArchitecture::Blackwell => "blackwell",
        DeviceArchitecture::Unknown => "unknown",
    }
}

fn enumerate_gpus(args: &Args) -> Result<Vec<GpuInfo>> {
    let nvml = match &args.nvml_lib_path {
        Some(p) => Nvml::builder()
            .lib_path(std::ffi::OsStr::new(p))
            .init()
            .context("NVML init failed with custom lib path")?,
        None => Nvml::init().context("NVML init failed (driver not loaded?)")?,
    };
    let count = nvml.device_count().context("nvmlDeviceGetCount failed")?;

    let exclude: std::collections::HashSet<u32> = args.exclude_indices.iter().copied().collect();
    let mut out = Vec::with_capacity(count as usize);

    for i in 0..count {
        let dev = nvml.device_by_index(i).context("device_by_index")?;
        let idx = dev.index().unwrap_or(i);
        if exclude.contains(&idx) {
            info!(gpu = idx, "skipping (exclude-indices)");
            continue;
        }
        let display_active = match dev.is_display_active() {
            Ok(v) => v,
            Err(NvmlError::NotSupported) => false,
            Err(e) => return Err(anyhow!("is_display_active({idx}) failed: {e}")),
        };
        if args.exclude_display_gpus && display_active {
            info!(gpu = idx, "skipping (display active)");
            continue;
        }
        let mem = dev.memory_info().context("memory_info")?;
        let cc = dev
            .cuda_compute_capability()
            .context("cuda_compute_capability")?;
        let arch = match dev.architecture() {
            Ok(a) => architecture_str(a).to_string(),
            Err(NvmlError::NotSupported) => "unknown".to_string(),
            Err(e) => return Err(anyhow!("architecture({idx}) failed: {e}")),
        };
        out.push(GpuInfo {
            index: idx,
            uuid: dev.uuid().context("uuid")?,
            name: dev.name().context("name")?,
            architecture: arch,
            memory_bytes: mem.total,
            display_active,
            compute_major: cc.major,
            compute_minor: cc.minor,
        });
    }
    Ok(out)
}

fn device_name_for(gpu: &GpuInfo) -> String {
    format!("gpu-{}", gpu.index)
}

fn cdi_id_for(args: &Args, gpu: &GpuInfo) -> String {
    format!("{}={}", args.cdi_kind, gpu.index)
}

fn build_resource_slice(args: &Args, gpus: &[GpuInfo]) -> resv1::ResourceSlice {
    let pool_name = args.node_name.clone();
    let devices: Vec<resv1::Device> = gpus
        .iter()
        .map(|g| {
            let mut attrs: BTreeMap<String, resv1::DeviceAttribute> = BTreeMap::new();
            attrs.insert(
                "index".into(),
                resv1::DeviceAttribute {
                    int: Some(g.index as i64),
                    ..Default::default()
                },
            );
            attrs.insert(
                "uuid".into(),
                resv1::DeviceAttribute {
                    string: Some(g.uuid.clone()),
                    ..Default::default()
                },
            );
            attrs.insert(
                "productName".into(),
                resv1::DeviceAttribute {
                    string: Some(g.name.clone()),
                    ..Default::default()
                },
            );
            attrs.insert(
                "architecture".into(),
                resv1::DeviceAttribute {
                    string: Some(g.architecture.clone()),
                    ..Default::default()
                },
            );
            attrs.insert(
                "displayActive".into(),
                resv1::DeviceAttribute {
                    bool: Some(g.display_active),
                    ..Default::default()
                },
            );
            attrs.insert(
                "cudaComputeMajor".into(),
                resv1::DeviceAttribute {
                    int: Some(g.compute_major as i64),
                    ..Default::default()
                },
            );
            attrs.insert(
                "cudaComputeMinor".into(),
                resv1::DeviceAttribute {
                    int: Some(g.compute_minor as i64),
                    ..Default::default()
                },
            );

            let mut capacity: BTreeMap<String, resv1::DeviceCapacity> = BTreeMap::new();
            capacity.insert(
                "memory".into(),
                resv1::DeviceCapacity {
                    value: Quantity(format!("{}", g.memory_bytes)),
                    request_policy: None,
                },
            );

            resv1::Device {
                name: device_name_for(g),
                attributes: Some(attrs),
                capacity: Some(capacity),
                ..Default::default()
            }
        })
        .collect();

    resv1::ResourceSlice {
        metadata: ObjectMeta {
            name: Some(format!("{}-{}", args.driver_name, args.node_name)),
            ..Default::default()
        },
        spec: resv1::ResourceSliceSpec {
            driver: args.driver_name.clone(),
            pool: resv1::ResourcePool {
                name: pool_name,
                generation: 1,
                resource_slice_count: 1,
            },
            node_name: Some(args.node_name.clone()),
            devices: Some(devices),
            ..Default::default()
        },
    }
}

fn build_device_class(args: &Args) -> Option<resv1::DeviceClass> {
    if args.device_class.is_empty() {
        return None;
    }
    let selectors = vec![resv1::DeviceSelector {
        cel: Some(resv1::CELDeviceSelector {
            expression: format!("device.driver == '{}'", args.driver_name),
        }),
    }];
    let extended = if args.extended_resource_name.is_empty() {
        None
    } else {
        Some(args.extended_resource_name.clone())
    };
    Some(resv1::DeviceClass {
        metadata: ObjectMeta {
            name: Some(args.device_class.clone()),
            ..Default::default()
        },
        spec: resv1::DeviceClassSpec {
            selectors: Some(selectors),
            extended_resource_name: extended,
            config: None,
        },
    })
}

async fn publish_loop(
    args: Args,
    gpus: Vec<GpuInfo>,
    mut shutdown: watch::Receiver<bool>,
) -> Result<()> {
    let client = Client::try_default()
        .await
        .context("kube client (in-cluster)")?;
    let pp = PatchParams::apply("nvidia-cdi-dra").force();

    let slice = build_resource_slice(&args, &gpus);
    let slices: Api<resv1::ResourceSlice> = Api::all(client.clone());
    let name = slice
        .metadata
        .name
        .clone()
        .ok_or_else(|| anyhow!("slice missing name"))?;

    if let Some(dc) = build_device_class(&args) {
        let dc_name = dc.metadata.name.clone().unwrap();
        let classes: Api<resv1::DeviceClass> = Api::all(client.clone());
        match classes.patch(&dc_name, &pp, &Patch::Apply(&dc)).await {
            Ok(_) => info!(name = %dc_name, "applied DeviceClass"),
            Err(e) => warn!(name = %dc_name, err = %e, "DeviceClass apply failed (continuing)"),
        }
    }

    loop {
        match slices.patch(&name, &pp, &Patch::Apply(&slice)).await {
            Ok(_) => info!(name = %name, devices = gpus.len(), "applied ResourceSlice"),
            Err(e) => warn!(err = %e, "ResourceSlice apply failed; will retry"),
        }
        select! {
            _ = sleep(Duration::from_secs(60)) => {}
            _ = shutdown.changed() => {
                if *shutdown.borrow() { break; }
            }
        }
    }

    info!("publish loop exiting; deleting ResourceSlice");
    let _ = slices
        .delete(&name, &kube::api::DeleteParams::default())
        .await;
    Ok(())
}

struct DraService {
    args: Args,
    client: Client,
    gpu_by_device_name: HashMap<String, GpuInfo>,
}

#[async_trait]
impl pb::dra::dra_plugin_server::DraPlugin for DraService {
    async fn node_prepare_resources(
        &self,
        req: Request<pb::dra::NodePrepareResourcesRequest>,
    ) -> Result<Response<pb::dra::NodePrepareResourcesResponse>, Status> {
        let mut out: HashMap<String, pb::dra::NodePrepareResourceResponse> = HashMap::new();
        for claim in &req.get_ref().claims {
            let resp = match self.prepare_one(claim).await {
                Ok(devs) => pb::dra::NodePrepareResourceResponse {
                    devices: devs,
                    error: String::new(),
                },
                Err(e) => pb::dra::NodePrepareResourceResponse {
                    devices: vec![],
                    error: format!("{e:#}"),
                },
            };
            out.insert(claim.uid.clone(), resp);
        }
        Ok(Response::new(pb::dra::NodePrepareResourcesResponse {
            claims: out,
        }))
    }

    async fn node_unprepare_resources(
        &self,
        req: Request<pb::dra::NodeUnprepareResourcesRequest>,
    ) -> Result<Response<pb::dra::NodeUnprepareResourcesResponse>, Status> {
        let mut out: HashMap<String, pb::dra::NodeUnprepareResourceResponse> = HashMap::new();
        for claim in &req.get_ref().claims {
            out.insert(
                claim.uid.clone(),
                pb::dra::NodeUnprepareResourceResponse {
                    error: String::new(),
                },
            );
        }
        Ok(Response::new(pb::dra::NodeUnprepareResourcesResponse {
            claims: out,
        }))
    }
}

impl DraService {
    async fn prepare_one(&self, claim: &pb::dra::Claim) -> Result<Vec<pb::dra::Device>> {
        let claims: Api<resv1::ResourceClaim> =
            Api::namespaced(self.client.clone(), &claim.namespace);
        let obj = claims
            .get(&claim.name)
            .await
            .with_context(|| format!("get ResourceClaim {}/{}", claim.namespace, claim.name))?;
        if obj.metadata.uid.as_deref() != Some(&claim.uid) {
            return Err(anyhow!(
                "uid mismatch for claim {}/{}",
                claim.namespace,
                claim.name
            ));
        }
        let alloc = obj
            .status
            .as_ref()
            .and_then(|s| s.allocation.as_ref())
            .ok_or_else(|| anyhow!("claim {}/{} has no allocation", claim.namespace, claim.name))?;
        let empty: Vec<resv1::DeviceRequestAllocationResult> = Vec::new();
        let results = alloc
            .devices
            .as_ref()
            .and_then(|d| d.results.as_ref())
            .unwrap_or(&empty);

        let mut out = Vec::new();
        for r in results {
            if r.driver != self.args.driver_name {
                continue;
            }
            let gpu = self
                .gpu_by_device_name
                .get(&r.device)
                .ok_or_else(|| anyhow!("unknown device {} from allocation", r.device))?;
            out.push(pb::dra::Device {
                request_names: vec![r.request.clone()],
                pool_name: r.pool.clone(),
                device_name: r.device.clone(),
                cdi_device_ids: vec![cdi_id_for(&self.args, gpu)],
            });
        }
        Ok(out)
    }
}

struct RegistrationService {
    name: String,
    endpoint: String,
}

#[async_trait]
impl pb::registration::registration_server::Registration for RegistrationService {
    async fn get_info(
        &self,
        _req: Request<pb::registration::InfoRequest>,
    ) -> Result<Response<pb::registration::PluginInfo>, Status> {
        Ok(Response::new(pb::registration::PluginInfo {
            r#type: "DRAPlugin".into(),
            name: self.name.clone(),
            endpoint: self.endpoint.clone(),
            supported_versions: vec![DRA_API_VERSION.into()],
        }))
    }

    async fn notify_registration_status(
        &self,
        req: Request<pb::registration::RegistrationStatus>,
    ) -> Result<Response<pb::registration::RegistrationStatusResponse>, Status> {
        let s = req.get_ref();
        if s.plugin_registered {
            info!(plugin = %self.name, "kubelet registered plugin");
        } else {
            error!(plugin = %self.name, err = %s.error, "kubelet rejected plugin registration");
        }
        Ok(Response::new(pb::registration::RegistrationStatusResponse {}))
    }
}

async fn serve_registration(
    socket: PathBuf,
    svc: RegistrationService,
    mut shutdown: watch::Receiver<bool>,
) -> Result<()> {
    if socket.exists() {
        std::fs::remove_file(&socket)?;
    }
    if let Some(parent) = socket.parent() {
        tokio::fs::create_dir_all(parent).await.ok();
    }
    let listener = UnixListener::bind(&socket)
        .with_context(|| format!("bind {}", socket.display()))?;
    let incoming = UnixListenerStream::new(listener);
    Server::builder()
        .add_service(
            pb::registration::registration_server::RegistrationServer::new(svc),
        )
        .serve_with_incoming_shutdown(incoming, async move {
            let _ = shutdown.changed().await;
        })
        .await?;
    Ok(())
}

async fn serve_dra(
    socket: PathBuf,
    svc: DraService,
    mut shutdown: watch::Receiver<bool>,
) -> Result<()> {
    if socket.exists() {
        std::fs::remove_file(&socket)?;
    }
    if let Some(parent) = socket.parent() {
        tokio::fs::create_dir_all(parent).await.ok();
    }
    let listener = UnixListener::bind(&socket)
        .with_context(|| format!("bind {}", socket.display()))?;
    let incoming = UnixListenerStream::new(listener);
    Server::builder()
        .add_service(pb::dra::dra_plugin_server::DraPluginServer::new(svc))
        .serve_with_incoming_shutdown(incoming, async move {
            let _ = shutdown.changed().await;
        })
        .await?;
    Ok(())
}

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    rustls::crypto::ring::default_provider()
        .install_default()
        .map_err(|_| anyhow!("rustls CryptoProvider already installed"))?;

    let args = Args::parse();
    if args.node_name.is_empty() {
        anyhow::bail!("--node-name (or NODE_NAME env) is required");
    }

    let gpus = enumerate_gpus(&args)?;
    if gpus.is_empty() {
        warn!("no GPUs found (after filters); driver will publish an empty ResourceSlice");
    } else {
        for g in &gpus {
            info!(
                index = g.index,
                name = %g.name,
                arch = %g.architecture,
                vram_mib = g.memory_bytes / (1024 * 1024),
                display = g.display_active,
                "discovered GPU"
            );
        }
    }
    let gpu_by_device_name: HashMap<String, GpuInfo> =
        gpus.iter().map(|g| (device_name_for(g), g.clone())).collect();

    let plugins_dir = Path::new(&args.kubelet_dir).join("plugins").join(&args.driver_name);
    let registry_dir = Path::new(&args.kubelet_dir).join("plugins_registry");
    tokio::fs::create_dir_all(&plugins_dir).await.ok();
    tokio::fs::create_dir_all(&registry_dir).await.ok();

    let dra_socket = plugins_dir.join("dra.sock");
    let reg_socket = registry_dir.join(format!("{}-reg.sock", args.driver_name));

    let (shutdown_tx, shutdown_rx) = watch::channel(false);

    // Spawn ResourceSlice publisher.
    let pub_handle = tokio::spawn(publish_loop(
        args.clone(),
        gpus.clone(),
        shutdown_rx.clone(),
    ));

    // Spawn DRA service.
    let client = Client::try_default().await.context("kube client for DRA")?;
    let dra_svc = DraService {
        args: args.clone(),
        client,
        gpu_by_device_name,
    };
    let dra_socket_clone = dra_socket.clone();
    let dra_shutdown = shutdown_rx.clone();
    let dra_handle = tokio::spawn(async move {
        if let Err(e) = serve_dra(dra_socket_clone, dra_svc, dra_shutdown).await {
            error!(err = %e, "DRA server exited");
        }
    });

    // Spawn registration service (advertises the DRA socket to kubelet).
    let reg_svc = RegistrationService {
        name: args.driver_name.clone(),
        endpoint: dra_socket.to_string_lossy().to_string(),
    };
    let reg_socket_clone = reg_socket.clone();
    let reg_shutdown = shutdown_rx.clone();
    let reg_handle = tokio::spawn(async move {
        if let Err(e) = serve_registration(reg_socket_clone, reg_svc, reg_shutdown).await {
            error!(err = %e, "registration server exited");
        }
    });

    info!(
        driver = %args.driver_name,
        node = %args.node_name,
        dra = %dra_socket.display(),
        reg = %reg_socket.display(),
        "nvidia-cdi DRA driver running"
    );

    tokio::signal::ctrl_c().await?;
    info!("shutdown signal received");
    let _ = shutdown_tx.send(true);
    let _ = tokio::time::timeout(Duration::from_secs(5), pub_handle).await;
    let _ = tokio::time::timeout(Duration::from_secs(5), dra_handle).await;
    let _ = tokio::time::timeout(Duration::from_secs(5), reg_handle).await;
    Ok(())
}

